'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, FileDown, Printer } from 'lucide-react';
import { createClient } from '../../lib/supabase';

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const dateLabel=(s:string)=>s?new Date(s+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'-';
const today=()=>new Date().toISOString().slice(0,10);

export default function LaporanPage(){
 const [loading,setLoading]=useState(true),[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>(null);
 const [ps,setPs]=useState<any[]>([]),[hs,setHs]=useState<any[]>([]),[es,setEs]=useState<any[]>([]),[cs,setCs]=useState<any[]>([]);
 const now=new Date(), first=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;
 const [from,setFrom]=useState(first),[to,setTo]=useState(today()),[plantation,setPlantation]=useState('all');
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/';return}setUser(user);const [pr,p,h,e,c]=await Promise.all([s.from('profiles').select('full_name,role').eq('id',user.id).single(),s.from('plantations').select('*').order('name'),s.from('harvests').select('*').order('harvest_date'),s.from('expenses').select('*,expense_categories(name)').order('expense_date'),s.from('maintenance').select('*').order('scheduled_date')]);setProfile(pr.data);setPs(p.data||[]);setHs(h.data||[]);setEs(e.data||[]);setCs(c.data||[]);setLoading(false)})()},[]);
 const data=useMemo(()=>{const ok=(d:string,id:number)=>d>=from&&d<=to&&(plantation==='all'||String(id)===plantation);const fh=hs.filter(h=>ok(h.harvest_date,h.plantation_id)),fe=es.filter(e=>ok(e.expense_date,e.plantation_id)),fc=cs.filter(c=>ok(c.scheduled_date,c.plantation_id));const selected=ps.filter(p=>plantation==='all'||String(p.id)===plantation);const kg=fh.reduce((a,h)=>a+Number(h.weight_kg),0);const revenue=fh.reduce((a,h)=>a+Number(h.weight_kg)*Number(h.price_per_kg)-Number(h.unloading_cost||0),0);const expense=fe.reduce((a,e)=>a+Number(e.amount),0)+fc.reduce((a,c)=>a+Number(c.cost||0),0);const area=selected.reduce((a,p)=>a+Number(p.area_ha||0),0);const perKebun=selected.map(p=>{const ph=fh.filter(h=>h.plantation_id===p.id),pe=fe.filter(e=>e.plantation_id===p.id),pc=fc.filter(c=>c.plantation_id===p.id);const pKg=ph.reduce((a,h)=>a+Number(h.weight_kg),0),rev=ph.reduce((a,h)=>a+Number(h.weight_kg)*Number(h.price_per_kg)-Number(h.unloading_cost||0),0),cost=pe.reduce((a,e)=>a+Number(e.amount),0)+pc.reduce((a,c)=>a+Number(c.cost||0),0);return {...p,kg:pKg,revenue:rev,cost,profit:rev-cost}});return {fh,fe,fc,kg,revenue,expense,profit:revenue-expense,area,perKebun}},[from,to,plantation,ps,hs,es,cs]);
 if(loading)return <div style={{padding:40,fontFamily:'Arial'}}>Memuat laporan…</div>;
 return <div className="reportPage"><div className="reportControls"><Link href="/" className="back"><ArrowLeft size={17}/> Dashboard</Link><div className="filters"><label>Dari<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Kebun<select value={plantation} onChange={e=>setPlantation(e.target.value)}><option value="all">Semua Kebun</option>{ps.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><button onClick={()=>window.print()}><FileDown size={18}/> Cetak / Simpan PDF</button></div>
 <article className="paper"><header><div><div className="logo">Sawit<span>Pro</span></div><p>Laporan Performa Kebun Kelapa Sawit</p></div><div className="meta"><b>Periode</b><br/>{dateLabel(from)} — {dateLabel(to)}<br/><small>Dibuat oleh {profile?.full_name||user?.email}</small></div></header>
 <section className="summary"><div><small>Total Tonase</small><strong>{(data.kg/1000).toFixed(2)} ton</strong></div><div><small>Produktivitas</small><strong>{(data.kg/1000/Math.max(data.area,0.01)).toFixed(2)} ton/ha</strong></div><div><small>Pendapatan</small><strong>{money(data.revenue)}</strong></div><div><small>Laba Bersih</small><strong>{money(data.profit)}</strong></div></section>
 <Section title="Ringkasan per Kebun"><table><thead><tr><th>Kebun</th><th>Luas</th><th>Tonase</th><th>Ton/Ha</th><th>Pendapatan</th><th>Biaya</th><th>Laba</th></tr></thead><tbody>{data.perKebun.map((p:any)=><tr key={p.id}><td><b>{p.name}</b><br/><small>{p.location||'-'}</small></td><td>{p.area_ha} ha</td><td>{(p.kg/1000).toFixed(2)} ton</td><td>{(p.kg/1000/Math.max(Number(p.area_ha),0.01)).toFixed(2)}</td><td>{money(p.revenue)}</td><td>{money(p.cost)}</td><td>{money(p.profit)}</td></tr>)}</tbody></table></Section>
 <Section title="Rincian Panen"><table><thead><tr><th>Tanggal</th><th>Kebun</th><th>Berat</th><th>Harga/kg</th><th>PKS</th><th>Pendapatan Bersih</th></tr></thead><tbody>{data.fh.map((h:any)=><tr key={h.id}><td>{dateLabel(h.harvest_date)}</td><td>{ps.find(p=>p.id===h.plantation_id)?.name||'-'}</td><td>{Number(h.weight_kg).toLocaleString('id-ID')} kg</td><td>{money(h.price_per_kg)}</td><td>{h.pks_destination||'-'}</td><td>{money(Number(h.weight_kg)*Number(h.price_per_kg)-Number(h.unloading_cost||0))}</td></tr>)}{!data.fh.length&&<tr><td colSpan={6}>Belum ada data panen.</td></tr>}</tbody></table></Section>
 <Section title="Rincian Biaya Operasional"><table><thead><tr><th>Tanggal</th><th>Kebun</th><th>Kategori</th><th>Penerima</th><th>Jumlah</th></tr></thead><tbody>{data.fe.map((e:any)=><tr key={e.id}><td>{dateLabel(e.expense_date)}</td><td>{ps.find(p=>p.id===e.plantation_id)?.name||'-'}</td><td>{e.expense_categories?.name||'-'}</td><td>{e.payee||'-'}</td><td>{money(e.amount)}</td></tr>)}{!data.fe.length&&<tr><td colSpan={5}>Belum ada biaya operasional.</td></tr>}</tbody></table></Section>
 <Section title="Perawatan"><table><thead><tr><th>Tanggal</th><th>Kebun</th><th>Kegiatan</th><th>Status</th><th>Biaya</th></tr></thead><tbody>{data.fc.map((c:any)=><tr key={c.id}><td>{dateLabel(c.scheduled_date)}</td><td>{ps.find(p=>p.id===c.plantation_id)?.name||'-'}</td><td>{c.activity_type}</td><td>{c.status==='completed'?'Selesai':'Terjadwal'}</td><td>{money(c.cost)}</td></tr>)}{!data.fc.length&&<tr><td colSpan={5}>Belum ada data perawatan.</td></tr>}</tbody></table></Section>
 <footer>SawitPro • Laporan dibuat {new Date().toLocaleString('id-ID')}</footer></article>
 <style jsx global>{`body{margin:0;background:#eef6f1}.reportPage{min-height:100vh;padding:28px;font-family:Arial,sans-serif;color:#103d32}.reportControls{max-width:1120px;margin:0 auto 18px;display:flex;gap:14px;align-items:end;flex-wrap:wrap}.reportControls .back{color:#087b5c;text-decoration:none;font-weight:700;margin-right:auto;display:flex;gap:6px;align-items:center}.filters{display:flex;gap:10px;flex-wrap:wrap}.filters label{font-size:12px;font-weight:700}.filters input,.filters select{display:block;margin-top:5px;padding:9px 10px;border:1px solid #c9ddd5;border-radius:9px;background:white}.reportControls button{border:0;border-radius:10px;background:#078a64;color:white;padding:11px 15px;font-weight:700;display:flex;gap:7px;align-items:center;cursor:pointer}.paper{max-width:1120px;margin:auto;background:white;border-radius:18px;padding:38px;box-shadow:0 12px 35px #173c2f18}.paper header{display:flex;justify-content:space-between;border-bottom:3px solid #0b8b65;padding-bottom:18px}.logo{font-size:30px;font-weight:900}.logo span{color:#11a878}.paper header p{margin:5px 0;color:#6a7f77}.meta{text-align:right;line-height:1.5}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.summary div{background:#eff9f4;border-left:4px solid #0aa174;padding:15px;border-radius:10px}.summary small{display:block;color:#657a72;margin-bottom:8px}.summary strong{font-size:18px}.reportSection{margin-top:28px}.reportSection h2{font-size:18px;margin-bottom:10px}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#edf6f2;text-align:left;padding:10px;border-bottom:1px solid #cfe0d9}td{padding:9px 10px;border-bottom:1px solid #e4ece8}footer{text-align:center;color:#71827b;font-size:11px;margin-top:35px;padding-top:15px;border-top:1px solid #dde7e2}@media(max-width:800px){.reportPage{padding:12px}.paper{padding:18px}.summary{grid-template-columns:1fr 1fr}.paper{overflow-x:auto}}@media print{body{background:white}.reportPage{padding:0}.reportControls{display:none!important}.paper{max-width:none;box-shadow:none;border-radius:0;padding:10mm}.reportSection{break-inside:auto}.reportSection h2{break-after:avoid}tr{break-inside:avoid}.summary{break-inside:avoid}@page{size:A4 landscape;margin:8mm}}`}</style></div>
}

function Section({title,children}:{title:string,children:any}){return <section className="reportSection"><h2>{title}</h2>{children}</section>}
